import "./globals.css";
import { Inter } from "next/font/google";
import MyFooter from "@/components/molecules/myFooter/myFooter";
import MyMenu from "@/components/molecules/myMenu/myMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ background: 'white' }}>
          <MyMenu />
          {children}
          <MyFooter />
        </body>
    </html>
  );
}
