import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import MyFooter from "@/components/molecules/myFooter/myFooter";
import MyMenu from "@/components/molecules/myMenu/myMenu";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ background: 'white' }}>
          <MyMenu />
          {children}
          <MyFooter />
          <Toaster
          position="bottom-center"
          toastOptions={{
            style: {
              padding: '16px',
              fontFamily: 'Roboto'
            },
            success: {
              iconTheme: {
                primary: 'white',
                secondary: 'green'
              },
              style: {
                backgroundColor: 'green',
                color: 'white'
              }
            },
            error: {
              style: {
                backgroundColor: 'red',
                color: 'white'
              }
            }
            
          }} 
          containerStyle={{
            bottom: 100
          }}/>
      </body>
    </html>
  );
}
