import { Inter } from 'next/font/google'
import MyFooter from '@/components/molecules/myFooter/myFooter';
import MyMenu from '@/components/molecules/myMenu/myMenu'
import { NextIntlClientProvider } from 'next-intl';


const inter = Inter({ subsets: ['latin'] })

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fr" }];
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface LayoutParams {
  locale: string;
}
export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: LayoutParams;
}) {
  let translations;
  try {
    translations = (await import(`../../languages/${params.locale}.json`))
      .default;
  } catch (error) {
    translations = (await import(`../../languages/en.json`)).default;
  }
  return (
    <html lang={params.locale}>
      <body style={{ backgroundColor: 'white' }}>
        <NextIntlClientProvider locale={params.locale} messages={translations}>
          <>
            <MyMenu />
            {children}
            <MyFooter />
          </>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
